type Product = {
  id: number;
  name: string;
  price: number;
  originalPrice?: number;
  rating: number;
  reviews: number;
  images: string[];
  colors: string[];
  isNew?: boolean;
  isBestSeller?: boolean;
  isFeatured?: boolean;
  category: string;
  stock: number;
  ageRange?: string;
  description?: string;
};

type ProductSpecs = {
  brand: string;
  countryOfOrigin: string;
  productType: string;
  materials: string;
  packContains: string;
};

type CompleteProduct = Product & {
  description: string;
  specifications: ProductSpecs;
};

export const allProducts: CompleteProduct[] = [
  {
    id: 1,
    name: "Organic Cotton Bodysuits (Pack of 5)",
    price: 3499,
    originalPrice: 3999,
    rating: 4.8,
    reviews: 142,
    images: [
      "/images/products/baby-clothing.png",
      "/images/products/bath-skincare.png",
      "/images/products/diapering.jpeg",
      "/images/products/feeding-nursing.jpeg",
      "/images/products/moms-care.jpeg",
    ],
    colors: ["white", "gray", "yellow"],
    isNew: true,
    isBestSeller: true,
    category: "clothing",
    stock: 42,
    ageRange: "0-6m",
    description:
      "Crafted from soft, breathable organic cotton, these bodysuits are ideal for your newborn’s delicate skin. Designed with a gentle envelope neckline for hassle-free dressing and convenient snap buttons for quick diaper changes, this essential set ensures all-day comfort and ease for both baby and parent.",
    specifications: {
      brand: "BabyComfy",
      countryOfOrigin: "India",
      productType: "Baby Clothing",
      materials: "100% Organic Cotton",
      packContains: "5 Bodysuits (White, Gray, Yellow)",
    },
  },
  {
    id: 2,
    name: "Baby Romper with Hat Set",
    price: 1799,
    rating: 4.5,
    reviews: 87,
    images: [
      "/images/products/baby-clothing.png",
      "/images/products/bath-skincare.png",
      "/images/products/diapering.jpeg",
      "/images/products/feeding-nursing.jpeg",
      "/images/products/moms-care.jpeg",
    ],
    colors: ["blue", "pink"],
    category: "clothing",
    stock: 15,
    ageRange: "6-12m",
    description:
      "Adorable romper and matching hat set made from soft fabric to keep your baby comfortable.",
    specifications: {
      brand: "TinyTrends",
      countryOfOrigin: "Bangladesh",
      productType: "Baby Clothing Set",
      materials: "Cotton-Spandex Blend",
      packContains: "1 Romper + 1 Hat",
    },
  },
  {
    id: 3,
    name: "Premium Baby Kimono Set",
    price: 2299,
    originalPrice: 2599,
    rating: 4.7,
    reviews: 64,
    images: [
      "/images/products/baby-clothing.png",
      "/images/products/bath-skincare.png",
      "/images/products/diapering.jpeg",
      "/images/products/feeding-nursing.jpeg",
      "/images/products/moms-care.jpeg",
    ],
    colors: ["white", "beige"],
    isNew: true,
    category: "clothing",
    stock: 28,
    ageRange: "0-3m",
    description:
      "Gentle kimono-style tops with side-snap closures for newborns, made from ultra-soft fabric.",
    specifications: {
      brand: "KimonoBaby",
      countryOfOrigin: "Japan",
      productType: "Newborn Clothing",
      materials: "100% Bamboo Viscose",
      packContains: "3 Kimono Sets",
    },
  },
  {
    id: 4,
    name: "Baby Sun Hat with UV Protection",
    price: 799,
    rating: 4.3,
    reviews: 56,
    images: [
      "/images/products/baby-clothing.png",
      "/images/products/bath-skincare.png",
      "/images/products/diapering.jpeg",
      "/images/products/feeding-nursing.jpeg",
      "/images/products/moms-care.jpeg",
    ],
    colors: ["white", "blue"],
    category: "clothing",
    stock: 39,
    ageRange: "0-12m",
    description:
      "Protective sun hat with UPF 50+ rating to shield delicate skin from harmful UV rays.",
    specifications: {
      brand: "SunSafe",
      countryOfOrigin: "USA",
      productType: "Baby Accessory",
      materials: "Nylon with UPF Coating",
      packContains: "1 Sun Hat",
    },
  },
  {
    id: 5,
    name: "Soft Sole Baby Shoes (Pair)",
    price: 1199,
    rating: 4.6,
    reviews: 92,
    images: [
      "/images/products/baby-clothing.png",
      "/images/products/bath-skincare.png",
      "/images/products/diapering.jpeg",
      "/images/products/feeding-nursing.jpeg",
      "/images/products/moms-care.jpeg",
    ],
    colors: ["pink", "blue"],
    category: "clothing",
    stock: 25,
    ageRange: "6-12m",
    description:
      "Flexible sole shoes that allow natural foot movement while protecting tiny feet.",
    specifications: {
      brand: "FirstSteps",
      countryOfOrigin: "Portugal",
      productType: "Baby Footwear",
      materials: "Soft Leather + Cotton Lining",
      packContains: "1 Pair of Shoes",
    },
  },
  {
    id: 6,
    name: "Baby Winter Jacket",
    price: 2899,
    originalPrice: 3299,
    rating: 4.7,
    reviews: 34,
    images: [
      "/images/products/baby-clothing.png",
      "/images/products/bath-skincare.png",
      "/images/products/diapering.jpeg",
      "/images/products/feeding-nursing.jpeg",
      "/images/products/moms-care.jpeg",
    ],
    colors: ["red", "navy"],
    category: "clothing",
    stock: 18,
    ageRange: "3-6m",
    description:
      "Insulated winter jacket with water-resistant outer layer and soft fleece lining.",
    specifications: {
      brand: "WinterWarm",
      countryOfOrigin: "Canada",
      productType: "Outerwear",
      materials: "Polyester Outer, Fleece Lining",
      packContains: "1 Jacket",
    },
  },
  {
    id: 7,
    name: "Cotton Baby Socks (Pack of 6)",
    price: 699,
    rating: 4.4,
    reviews: 128,
    images: [
      "/images/products/baby-clothing.png",
      "/images/products/bath-skincare.png",
      "/images/products/diapering.jpeg",
      "/images/products/feeding-nursing.jpeg",
      "/images/products/moms-care.jpeg",
    ],
    colors: ["multi"],
    category: "clothing",
    stock: 50,
    ageRange: "24-36m",
    description:
      "Breathable cotton socks with non-slip grips to keep tiny feet warm and safe.",
    specifications: {
      brand: "SockHuggers",
      countryOfOrigin: "India",
      productType: "Baby Hosiery",
      materials: "100% Cotton",
      packContains: "6 Pairs of Socks",
    },
  },
  {
    id: 8,
    name: "Baby Denim Overalls",
    price: 2499,
    rating: 4.5,
    reviews: 76,
    images: [
      "/images/products/baby-clothing.png",
      "/images/products/bath-skincare.png",
      "/images/products/diapering.jpeg",
      "/images/products/feeding-nursing.jpeg",
      "/images/products/moms-care.jpeg",
    ],
    colors: ["blue", "black"],
    category: "clothing",
    stock: 22,
    ageRange: "12-24m",
    description:
      "Stylish yet practical denim overalls with adjustable straps for growing babies.",
    specifications: {
      brand: "DenimTots",
      countryOfOrigin: "Turkey",
      productType: "Baby Clothing",
      materials: "Soft Denim (98% Cotton, 2% Spandex)",
      packContains: "1 Overalls",
    },
  },
  {
    id: 9,
    name: "Montessori Wooden Activity Cube",
    price: 4999,
    rating: 4.9,
    reviews: 203,
    images: [
      "/images/products/baby-clothing.png",
      "/images/products/bath-skincare.png",
      "/images/products/diapering.jpeg",
      "/images/products/feeding-nursing.jpeg",
      "/images/products/moms-care.jpeg",
    ],
    colors: ["natural"],
    isBestSeller: true,
    category: "toys",
    stock: 8,
    ageRange: "6-24m",
    description:
      "Five-sided activity center with bead maze, shape sorter, spinning gears and more for developmental play.",
    specifications: {
      brand: "EduPlay",
      countryOfOrigin: "Germany",
      productType: "Educational Toy",
      materials: "Solid Beech Wood, Non-toxic Paints",
      packContains: "1 Activity Cube",
    },
  },
  {
    id: 10,
    name: "Sensory Teething Toys Set",
    price: 1299,
    rating: 4.6,
    reviews: 156,
    images: [
      "/images/products/baby-clothing.png",
      "/images/products/bath-skincare.png",
      "/images/products/diapering.jpeg",
      "/images/products/feeding-nursing.jpeg",
      "/images/products/moms-care.jpeg",
    ],
    colors: ["multi"],
    category: "toys",
    stock: 34,
    ageRange: "3-12m",
    description:
      "BPA-free textured teethers designed to soothe sore gums while stimulating senses.",
    specifications: {
      brand: "GumSoothers",
      countryOfOrigin: "USA",
      productType: "Teething Toy",
      materials: "Food-grade Silicone",
      packContains: "4 Different Teethers",
    },
  },
  {
    id: 11,
    name: "Baby Piano Play Gym",
    price: 3599,
    originalPrice: 3999,
    rating: 4.8,
    reviews: 98,
    images: [
      "/images/products/baby-clothing.png",
      "/images/products/bath-skincare.png",
      "/images/products/diapering.jpeg",
      "/images/products/feeding-nursing.jpeg",
      "/images/products/moms-care.jpeg",
    ],
    colors: ["multi"],
    isNew: true,
    category: "toys",
    stock: 12,
    ageRange: "0-12m",
    description:
      "Interactive play gym with removable piano keyboard that responds to kicks and touches.",
    specifications: {
      brand: "PlayTunes",
      countryOfOrigin: "France",
      productType: "Activity Gym",
      materials: "Polyester Fabric, ABS Plastic",
      packContains: "1 Play Mat, 1 Removable Piano, 3 Hanging Toys",
    },
  },
  {
    id: 12,
    name: "Stacking Rings Toy",
    price: 899,
    rating: 4.5,
    reviews: 87,
    images: [
      "/images/products/baby-clothing.png",
      "/images/products/bath-skincare.png",
      "/images/products/diapering.jpeg",
      "/images/products/feeding-nursing.jpeg",
      "/images/products/moms-care.jpeg",
    ],
    colors: ["multi"],
    category: "toys",
    stock: 45,
    ageRange: "6-18m",
    description:
      "Classic developmental toy with colorful rings to stack on a tapered pole.",
    specifications: {
      brand: "FirstToys",
      countryOfOrigin: "China",
      productType: "Stacking Toy",
      materials: "BPA-free Plastic",
      packContains: "1 Base + 6 Stacking Rings",
    },
  },
  {
    id: 13,
    name: "Soft Plush Rattle Set",
    price: 1499,
    rating: 4.7,
    reviews: 112,
    images: [
      "/images/products/baby-clothing.png",
      "/images/products/bath-skincare.png",
      "/images/products/diapering.jpeg",
      "/images/products/feeding-nursing.jpeg",
      "/images/products/moms-care.jpeg",
    ],
    colors: ["multi"],
    category: "toys",
    stock: 28,
    ageRange: "0-6m",
    description:
      "Gentle first rattles with crinkle fabric, teething edges and soft jingle sounds.",
    specifications: {
      brand: "CuddleBugs",
      countryOfOrigin: "South Korea",
      productType: "Infant Toy",
      materials: "Plush Fabric, PP Plastic",
      packContains: "3 Different Rattles",
    },
  },
  {
    id: 14,
    name: "Baby First Book Set",
    price: 1799,
    rating: 4.8,
    reviews: 65,
    images: [
      "/images/products/baby-clothing.png",
      "/images/products/bath-skincare.png",
      "/images/products/diapering.jpeg",
      "/images/products/feeding-nursing.jpeg",
      "/images/products/moms-care.jpeg",
    ],
    colors: ["multi"],
    category: "toys",
    stock: 37,
    ageRange: "12-24m",
    description:
      "Indestructible fabric books with high-contrast images to stimulate early visual development.",
    specifications: {
      brand: "TinyReaders",
      countryOfOrigin: "UK",
      productType: "Educational Book",
      materials: "Fabric, Non-toxic Ink",
      packContains: "4 Fabric Books",
    },
  },
  {
    id: 15,
    name: "Anti-Colic Baby Bottle Set",
    price: 2799,
    originalPrice: 3299,
    rating: 4.7,
    reviews: 98,
    images: [
      "/images/products/baby-clothing.png",
      "/images/products/bath-skincare.png",
      "/images/products/diapering.jpeg",
      "/images/products/feeding-nursing.jpeg",
      "/images/products/moms-care.jpeg",
    ],
    colors: ["pink", "blue"],
    isNew: true,
    category: "feeding",
    stock: 22,
    ageRange: "0-12m",
    description:
      "Vented bottles designed to reduce air intake and prevent colic, gas and spit-up.",
    specifications: {
      brand: "ColicFree",
      countryOfOrigin: "Switzerland",
      productType: "Feeding Bottle",
      materials: "Medical-grade Silicone, PP Plastic",
      packContains: "4 Bottles (150ml each), 8 Nipples, Cleaning Brush",
    },
  },
  {
    id: 16,
    name: "Insulated Baby Food Jar",
    price: 899,
    rating: 4.4,
    reviews: 45,
    images: [
      "/images/products/baby-clothing.png",
      "/images/products/bath-skincare.png",
      "/images/products/diapering.jpeg",
      "/images/products/feeding-nursing.jpeg",
      "/images/products/moms-care.jpeg",
    ],
    colors: ["green"],
    category: "feeding",
    stock: 50,
    ageRange: "6-24m",
    description:
      "Stainless steel jar keeps purees warm for 4 hours or cold for 6 hours on-the-go.",
    specifications: {
      brand: "FreshTots",
      countryOfOrigin: "USA",
      productType: "Food Container",
      materials: "304 Stainless Steel, BPA-free Plastic Lid",
      packContains: "1 Jar (180ml capacity)",
    },
  },
  {
    id: 17,
    name: "Baby Feeding Spoon Set",
    price: 599,
    rating: 4.3,
    reviews: 78,
    images: [
      "/images/products/baby-clothing.png",
      "/images/products/bath-skincare.png",
      "/images/products/diapering.jpeg",
      "/images/products/feeding-nursing.jpeg",
      "/images/products/moms-care.jpeg",
    ],
    colors: ["pink", "blue"],
    category: "feeding",
    stock: 60,
    ageRange: "4-24m",
    description:
      "Soft-tip spoons with heat-sensitive color change to warn if food is too hot.",
    specifications: {
      brand: "FirstBites",
      countryOfOrigin: "Germany",
      productType: "Feeding Utensils",
      materials: "Silicone Head, PP Handle",
      packContains: "4 Spoons (2 Starter, 2 Toddler)",
    },
  },
  {
    id: 18,
    name: "Silicone Baby Bibs (Pack of 3)",
    price: 1299,
    rating: 4.6,
    reviews: 134,
    images: [
      "/images/products/baby-clothing.png",
      "/images/products/bath-skincare.png",
      "/images/products/diapering.jpeg",
      "/images/products/feeding-nursing.jpeg",
      "/images/products/moms-care.jpeg",
    ],
    colors: ["blue", "pink", "gray"],
    category: "feeding",
    stock: 42,
    ageRange: "4-24m",
    description:
      "Waterproof bibs with deep pocket to catch spills and food debris during meals.",
    specifications: {
      brand: "MessFree",
      countryOfOrigin: "Italy",
      productType: "Feeding Accessory",
      materials: "Food-grade Silicone",
      packContains: "3 Bibs + Storage Pouch",
    },
  },
  {
    id: 19,
    name: "Electric Baby Food Maker",
    price: 4599,
    originalPrice: 4999,
    rating: 4.8,
    reviews: 56,
    images: [
      "/images/products/baby-clothing.png",
      "/images/products/bath-skincare.png",
      "/images/products/diapering.jpeg",
      "/images/products/feeding-nursing.jpeg",
      "/images/products/moms-care.jpeg",
    ],
    colors: ["white"],
    category: "feeding",
    stock: 15,
    ageRange: "4-12m",
    description:
      "All-in-one steamer and blender to prepare fresh, preservative-free baby food.",
    specifications: {
      brand: "NutriBaby",
      countryOfOrigin: "France",
      productType: "Kitchen Appliance",
      materials: "BPA-free Plastic, Stainless Steel Blades",
      packContains: "Main Unit, 3 Storage Containers, Recipe Book",
    },
  },
  {
    id: 20,
    name: "Musical Mobile for Crib",
    price: 3599,
    rating: 4.8,
    reviews: 132,
    images: [
      "/images/products/baby-clothing.png",
      "/images/products/bath-skincare.png",
      "/images/products/diapering.jpeg",
      "/images/products/feeding-nursing.jpeg",
      "/images/products/moms-care.jpeg",
    ],
    colors: ["white"],
    isBestSeller: true,
    category: "nursery",
    stock: 12,
    ageRange: "0-12m",
    description:
      "Soothing mobile with 5 classical melodies and gentle rotating plush animals.",
    specifications: {
      brand: "DreamyNights",
      countryOfOrigin: "USA",
      productType: "Nursery Decor",
      materials: "Plush Toys, ABS Plastic",
      packContains: "Mobile Unit, 5 Plush Characters, Remote Control",
    },
  },
  {
    id: 21,
    name: "Organic Cotton Swaddle Blanket",
    price: 1499,
    rating: 4.9,
    reviews: 287,
    images: [
      "/images/products/baby-clothing.png",
      "/images/products/bath-skincare.png",
      "/images/products/diapering.jpeg",
      "/images/products/feeding-nursing.jpeg",
      "/images/products/moms-care.jpeg",
    ],
    colors: ["gray", "mint"],
    category: "nursery",
    stock: 37,
    ageRange: "0-6m",
    description:
      "Breathable, lightweight swaddle perfect for regulating baby's temperature.",
    specifications: {
      brand: "SwaddleMe",
      countryOfOrigin: "India",
      productType: "Swaddling Blanket",
      materials: "100% Organic Cotton",
      packContains: "1 Blanket (120cm x 120cm)",
    },
  },
  {
    id: 22,
    name: "Baby Night Light Projector",
    price: 2299,
    rating: 4.7,
    reviews: 89,
    images: [
      "/images/products/baby-clothing.png",
      "/images/products/bath-skincare.png",
      "/images/products/diapering.jpeg",
      "/images/products/feeding-nursing.jpeg",
      "/images/products/moms-care.jpeg",
    ],
    colors: ["white", "blue"],
    category: "nursery",
    stock: 24,
    ageRange: "0-24m",
    description:
      "Multi-function projector that displays stars while playing white noise or lullabies.",
    specifications: {
      brand: "StarGlow",
      countryOfOrigin: "South Korea",
      productType: "Night Light",
      materials: "ABS Plastic, LED Lights",
      packContains: "Projector Base, AC Adapter",
    },
  },
  {
    id: 23,
    name: "Waterproof Crib Mattress",
    price: 4999,
    originalPrice: 5499,
    rating: 4.8,
    reviews: 76,
    images: [
      "/images/products/baby-clothing.png",
      "/images/products/bath-skincare.png",
      "/images/products/diapering.jpeg",
      "/images/products/feeding-nursing.jpeg",
      "/images/products/moms-care.jpeg",
    ],
    colors: ["white"],
    category: "nursery",
    stock: 9,
    ageRange: "0-24m",
    description:
      "Hypoallergenic mattress with medical-grade waterproof coating and breathable core.",
    specifications: {
      brand: "SafeSleep",
      countryOfOrigin: "USA",
      productType: "Crib Mattress",
      materials: "Waterproof PU Cover, High-density Foam",
      packContains: "1 Mattress (120x60cm)",
    },
  },
  {
    id: 24,
    name: "Baby Nursery Decor Set",
    price: 3299,
    rating: 4.6,
    reviews: 43,
    images: [
      "/images/products/baby-clothing.png",
      "/images/products/bath-skincare.png",
      "/images/products/diapering.jpeg",
      "/images/products/feeding-nursing.jpeg",
      "/images/products/moms-care.jpeg",
    ],
    colors: ["neutral"],
    category: "nursery",
    stock: 18,
    ageRange: "0-24m",
    description:
      "Coordinating wall art, name sign and growth chart in gender-neutral designs.",
    specifications: {
      brand: "NurseryDecor",
      countryOfOrigin: "UK",
      productType: "Wall Decor",
      materials: "FSC-certified Wood, Non-toxic Paint",
      packContains: "3 Wall Art Pieces, Growth Chart, Hanging Hardware",
    },
  },
  {
    id: 25,
    name: "Baby Bath Tub with Support",
    price: 2299,
    originalPrice: 2699,
    rating: 4.5,
    reviews: 76,
    images: [
      "/images/products/baby-clothing.png",
      "/images/products/bath-skincare.png",
      "/images/products/diapering.jpeg",
      "/images/products/feeding-nursing.jpeg",
      "/images/products/moms-care.jpeg",
    ],
    colors: ["white"],
    isNew: true,
    category: "bath",
    stock: 18,
    ageRange: "0-12m",
    description:
      "Ergonomic tub with contoured support for newborns and anti-slip base for safety.",
    specifications: {
      brand: "SplashEasy",
      countryOfOrigin: "Germany",
      productType: "Bathing Tub",
      materials: "PP Plastic, Soft TPU Support",
      packContains: "1 Tub, 1 Hanging Hook",
    },
  },
  {
    id: 26,
    name: "Organic Baby Shampoo Set",
    price: 1299,
    rating: 4.7,
    reviews: 143,
    images: [
      "/images/products/baby-clothing.png",
      "/images/products/bath-skincare.png",
      "/images/products/diapering.jpeg",
      "/images/products/feeding-nursing.jpeg",
      "/images/products/moms-care.jpeg",
    ],
    colors: ["clear"],
    category: "bath",
    stock: 42,
    ageRange: "0-24m",
    description:
      "Tear-free formula with organic calendula and chamomile to gently cleanse and moisturize.",
    specifications: {
      brand: "PureBaby",
      countryOfOrigin: "France",
      productType: "Bath Products",
      materials: "Organic Plant Extracts",
      packContains: "Shampoo (200ml), Body Wash (200ml), Lotion (200ml)",
    },
  },
  {
    id: 27,
    name: "Hooded Baby Towel",
    price: 999,
    rating: 4.6,
    reviews: 98,
    images: [
      "/images/products/baby-clothing.png",
      "/images/products/bath-skincare.png",
      "/images/products/diapering.jpeg",
      "/images/products/feeding-nursing.jpeg",
      "/images/products/moms-care.jpeg",
    ],
    colors: ["blue", "pink"],
    category: "bath",
    stock: 31,
    ageRange: "0-24m",
    description:
      "Ultra-absorbent hooded towel with cute animal ears for fun after-bath snuggles.",
    specifications: {
      brand: "CuddleDry",
      countryOfOrigin: "Turkey",
      productType: "Bath Towel",
      materials: "100% Bamboo Fiber",
      packContains: "1 Towel (75cm x 100cm)",
    },
  },
  {
    id: 28,
    name: "Lightweight Baby Stroller",
    price: 8999,
    originalPrice: 9999,
    rating: 4.8,
    reviews: 89,
    images: [
      "/images/products/baby-clothing.png",
      "/images/products/bath-skincare.png",
      "/images/products/diapering.jpeg",
      "/images/products/feeding-nursing.jpeg",
      "/images/products/moms-care.jpeg",
    ],
    colors: ["black", "navy"],
    isBestSeller: true,
    category: "gear",
    stock: 7,
    ageRange: "0-36m",
    description:
      "Compact yet sturdy stroller with one-hand fold mechanism and all-wheel suspension.",
    specifications: {
      brand: "GoLight",
      countryOfOrigin: "UK",
      productType: "Stroller",
      materials: "Aluminum Frame, Polyester Fabric",
      packContains: "Stroller, Rain Cover, Storage Basket",
    },
  },
  {
    id: 29,
    name: "Ergonomic Baby Carrier",
    price: 4599,
    rating: 4.9,
    reviews: 201,
    images: [
      "/images/products/baby-clothing.png",
      "/images/products/bath-skincare.png",
      "/images/products/diapering.jpeg",
      "/images/products/feeding-nursing.jpeg",
      "/images/products/moms-care.jpeg",
    ],
    colors: ["gray", "khaki"],
    category: "gear",
    stock: 14,
    ageRange: "0-24m",
    description:
      "HIP-certified carrier that supports proper spine and hip development in all carry positions.",
    specifications: {
      brand: "CarryComfort",
      countryOfOrigin: "Sweden",
      productType: "Baby Carrier",
      materials: "Breathable Mesh, Reinforced Buckles",
      packContains: "Carrier, Infant Insert, Storage Bag",
    },
  },
  {
    id: 30,
    name: "Car Seat & Stroller Combo",
    price: 12999,
    originalPrice: 14999,
    rating: 4.7,
    reviews: 67,
    images: [
      "/images/products/baby-clothing.png",
      "/images/products/bath-skincare.png",
      "/images/products/diapering.jpeg",
      "/images/products/feeding-nursing.jpeg",
      "/images/products/moms-care.jpeg",
    ],
    colors: ["black"],
    category: "gear",
    stock: 5,
    ageRange: "0-36m",
    description:
      "Premium travel system with safety-certified car seat that clicks into matching stroller base.",
    specifications: {
      brand: "SafeRide",
      countryOfOrigin: "Germany",
      productType: "Travel System",
      materials: "Polyester, Steel Frame, Impact-resistant Plastic",
      packContains: "1 Car Seat, 1 Stroller Base, Rain Cover",
    },
  },
];
